### ISSUE TITLE
Not enough values to unpack?

### ISSUE THREAD

**Issue by conepi** [vfnm/Poe-API-Server#24]
I've been encountering an issue which I can't seem to make heads or tails of, admittedly:

```
Poe API Server 0.5 by vfnm is up to date
 * Serving Flask app 'app'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.69.159:5000
Press CTRL+C to quit
[2023-08-04 08:41:53,059] ERROR in app: Exception on /v2/driver/sage/models [GET]
Traceback (most recent call last):
  File "Lib\site-packages\flask\app.py", line 2190, in wsgi_app
  File "Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
  File "Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
  File "Lib\site-packages\flask\app.py", line 1469, in dispatch_request
  File "app.py", line 40, in models
ValueError: not enough values to unpack (expected 2, got 1)
192.168.69.159 - - [04/Aug/2023 08:41:53] "GET /v2/driver/sage/models HTTP/1.1" 500 -
```
Both SillyTavern and the API server are updated to full, though I'm running through Windows so I'm unsure if that does anything to it. Haven't found any closed issues like it.

**Comment by vfnm** [comment]
Follow the updated guide.
